# Generated by Django 4.1.5 on 2023-01-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='branch',
            field=models.TextField(default=''),
        ),
    ]
